# Generated by Django 4.1.1 on 2022-09-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
