# Generated by Django 4.1.1 on 2022-09-15 17:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='')),
                ('bio', models.CharField(max_length=500)),
                ('intro', models.TextField(max_length=1500)),
                ('about_me', models.TextField(max_length=5000)),
                ('profile_photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile_photo')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resume',
        ),
    ]
