# Generated by Django 4.1.1 on 2022-09-15 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0002_myinfo_remove_profile_about_me_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
