# Generated by Django 4.1.1 on 2022-09-16 09:37

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0003_alter_profile_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('purpose', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('short_description', models.CharField(max_length=150)),
                ('summary', models.TextField(max_length=1000)),
                ('long_description', models.TextField(max_length=5000)),
                ('featured_img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Featured image')),
                ('screenshot', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Screenshot')),
                ('screenshot2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Screenshot2')),
                ('screenshot3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Screenshot3')),
                ('live_link', models.URLField(max_length=300)),
                ('rated', models.PositiveIntegerField()),
                ('rating', models.ManyToManyField(to='benie_app.rating')),
                ('technologies', models.ManyToManyField(to='benie_app.technology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=1500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benie_app.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
