# Generated by Django 4.1.1 on 2022-09-16 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0004_technology_rating_project_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='benie_app.project'),
        ),
    ]
