# Generated by Django 4.1.1 on 2022-12-30 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0005_remove_project_rating_rating_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(blank=True, choices=[('like', 'like'), ('dislike', 'dislike')], default='', max_length=60, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='rated',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screenshot2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screenshot3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='purpose',
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='commented_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='project',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benie_app.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_img',
            field=models.URLField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='long_description',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot',
            field=models.URLField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='reaction',
            name='project',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benie_app.project'),
        ),
    ]
