# Generated by Django 4.1.1 on 2023-01-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(default='', max_length=150),
        ),
    ]
