# Generated by Django 4.1.1 on 2023-01-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0009_feature_project_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='feature',
            new_name='features',
        ),
    ]
